apiVersion: v1
kind: Service
metadata:
  name: ai-finops-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ai-finops-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
