apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-finops-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ai-finops-app
  template:
    metadata:
      labels:
        app: ai-finops-app
    spec:
      containers:
        - name: ai-finops-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
