apiVersion: v1
kind: Service
metadata:
  name: ai-finops-frontend
spec:
  type: {{ .Values.frontendService.type }}
  selector:
    app: ai-finops-frontend
  ports:
    - port: {{ .Values.frontendService.port }}
      targetPort: {{ .Values.frontendService.port }}
      nodePort: {{ .Values.frontendService.nodePort }}
