name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build, Test & Publish Docker Images
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/impesud

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate dynamic tag
        id: tag
        run: |
          echo "CI_TAG=ci-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
          echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install backend dependencies & run tests
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pytest --maxfail=1 --disable-warnings -q

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install frontend dependencies & run tests
        working-directory: frontend
        run: |
          npm ci
          npm run lint
          npm test 

      - name: Log in to GitHub Container Registry
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        if: ${{ github.event_name == 'push' }}
        uses: docker/setup-buildx-action@v3

      - name: Build & push backend image
        if: ${{ github.event_name == 'push' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/ai-finops-platform-app:${{ env.CI_TAG }}
            ${{ env.REGISTRY }}/ai-finops-platform-app:latest

      - name: Build & push frontend image
        if: ${{ github.event_name == 'push' }}
        uses: docker/build-push-action@v5
        with:
          context: frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/ai-finops-platform-frontend:${{ env.CI_TAG }}
            ${{ env.REGISTRY }}/ai-finops-platform-frontend:latest


